# Generated by Django 3.1.1 on 2020-09-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dummi_videos', models.FileField(null=True, upload_to='post')),
            ],
        ),
    ]
