# Generated by Django 3.1.1 on 2020-09-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_content',
            old_name='dummi_videos',
            new_name='video',
        ),
    ]
