# Generated by Django 3.1.1 on 2020-09-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200917_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_content',
            name='video',
            field=models.FileField(null=True, upload_to=None),
        ),
    ]
