# Generated by Django 3.1.1 on 2020-09-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200917_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_content',
            name='video',
            field=models.FileField(null=True, upload_to='post'),
        ),
    ]
