# Generated by Django 3.1.1 on 2020-09-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_mat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_content',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
